waypoint_reconfigure:
  # 変更後のパラメータ
  global_inflation_radius: 0.5
  global_cost_scaling_factor: 3.0
  local_inflation_radius: 0.3
  local_cost_scaling_factor: 3.0

  # 変更前のパラメータ
  prev_global_inflation_radius: 1.25
  prev_global_cost_scaling_factor: 3.0
  prev_local_inflation_radius: 0.3
  prev_local_cost_scaling_factor: 3.0