teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.2

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 1.0

    enable_button: 4
    enable_turbo_button: 5  # L1 shoulder button
