slam_toolbox:
  ros__parameters:

    # --- プラグインのパラメータ ---
    solver_plugin: solver_plugins::CeresSolver # SLAM最適化に使用されるソルバー（CeresSolver）。
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY # Ceresで使用される線形ソルバー。大規模問題に適したもの。
    ceres_preconditioner: SCHUR_JACOBI # 前処理にSchur補前処理を使用。
    ceres_trust_strategy: LEVENBERG_MARQUARDT # 最適化アルゴリズムにLevenberg-Marquardt法を指定。
    ceres_dogleg_type: TRADITIONAL_DOGLEG # Dogleg法の種類。従来型のDogleg法を使用。
    ceres_loss_function: None # 外れ値処理の損失関数。Noneは未使用を意味する。

    # --- ROSのパラメータ ---
    odom_frame: odom # オドメトリフレームの名前（例: "odom"）。
    map_frame: map # マップフレームの名前（例: "map"）。
    base_frame: base_footprint # ロボットの基底フレーム名（例: "base_footprint"）。
    scan_topic: /surestar_scan # LiDARスキャンデータが配信されるトピック名。
    mode: mapping # 動作モード。mapping（地図作成）またはlocalization（位置推定）。

    # --- マップ作成の開始位置に関する設定（任意） ---
    map_start_pose: [0.0, 0.0, 0.0] # 地図作成を開始する位置（x, y, yaw）。
    map_start_at_dock: true # ドッキング地点から地図作成を開始するか。

    # --- デバッグ設定 ---
    debug_logging: false # デバッグ情報をログに出力するかどうか。
    debug_map_save: true # デバッグ用に地図を定期保存するかどうか。
    debug_create_image: true # デバッグ用にマップ画像を生成するかどうか。
    debug_interval: 10.0 # デバッグデータの出力間隔（秒単位）。

    # --- 地図更新とスキャン設定 ---
    throttle_scans: 1 # スキャンの使用頻度。1は全スキャンを使用。
    transform_publish_period: 0.1 # 0.02 トランスフォームの公開間隔。0で公開しない。
    map_update_interval: 5.0 # 地図の更新間隔（秒単位）。
    resolution: 0.1 # 地図の解像度（例: 0.1mごとに分解）。
    max_laser_range: 200.0 # LiDARの最大距離（メートル）。
    minimum_time_interval: 0.5 # スキャン間の最小時間間隔（秒）。
    transform_timeout: 0.2 # トランスフォームのタイムアウト（秒）。
    tf_buffer_duration: 30.0 # TFバッファの保持期間（秒）。
    stack_size_to_use: 40000000 # 大きな地図のシリアライズに使用されるスタックサイズ。
    enable_interactive_mode: true # インタラクティブモードを有効にするかどうか。

    # --- マッチングとリンク設定 ---
    use_scan_matching: false # スキャンマッチングを使用するかどうか。false:オドメトリを信頼。
    use_scan_barycenter: false # スキャンの重心を使用するかどうか。
    minimum_travel_distance: 0.3 # 0.3 スキャン間での最小移動距離（メートル）。
    minimum_travel_heading: 0.3 # 0.5 スキャン間での最小方向変化量（ラジアン）。
    scan_buffer_size: 30 # スキャンのバッファサイズ。
    scan_buffer_maximum_scan_distance: 10.0 # バッファ内の最大スキャン距離（メートル）。
    link_match_minimum_response_fine: 1.0 # 細かいリンクマッチングの最小応答値。
    link_scan_maximum_distance: 1.5 # リンクスキャンの最大距離（メートル）。
    loop_search_maximum_distance: 3000.0 # ループ検索の最大距離（メートル）。
    do_loop_closing: true # ループクロージングを行うかどうか。

    # --- ループクロージャ設定 ---
    loop_match_minimum_chain_size: 10 # ループマッチングの最小チェーンサイズ。
    loop_match_maximum_variance_coarse: 3.0 # 粗いループマッチングの最大分散。
    loop_match_minimum_response_coarse: 0.35 # 粗いループマッチングの最小応答値。
    loop_match_minimum_response_fine: 1.0 # 0.45 細かいループマッチングの最小応答値。
    loop_closure_enable_logging: true # ループクロージャのロギングを有効にするかどうか。
    loop_closure_variance_threshold: 100.0 # 1.0 ループクロージャの分散しきい値。

    # --- 相関パラメータ ---
    correlation_search_space_dimension: 0.3 # 0.5 相関検索空間のサイズ（メートル）。
    correlation_search_space_resolution: 0.01 # 相関検索空間の解像度（メートル）。
    correlation_search_space_smear_deviation: 0.1 # 相関検索空間のスミア偏差。
    correlation_search_depth: 3 # 相関検索の深さレベル。

    # --- ループクロージャの相関パラメータ ---
    loop_search_space_dimension: 8.0 # ループ検索空間のサイズ（メートル）。
    loop_search_space_resolution: 0.05 # ループ検索空間の解像度（メートル）。
    loop_search_space_smear_deviation: 0.03 # ループ検索空間のスミア偏差。
    loop_closure_correlation_threshold: 0.9 # ループクロージャの相関しきい値。

    # --- スキャンマッチャ設定 ---
    distance_variance_penalty: 1.5 # 距離の分散に対するペナルティ。
    angle_variance_penalty: 1.5 # 1.5 角度の分散に対するペナルティ。
    fine_search_angle_offset: 0.00349 # 細かい検索の角度オフセット（ラジアン）。
    coarse_search_angle_offset: 0.349 # 粗い検索の角度オフセット（ラジアン）。
    coarse_angle_resolution: 0.0349 # 粗い検索の角度解像度（ラジアン）。
    minimum_angle_penalty: 1.2 # 最小角度ペナルティ。
    minimum_distance_penalty: 0.5 # 最小距離ペナルティ。
    use_response_expansion: true # 応答拡張を使用するかどうか。

    # --- マップ保存設定 ---
    save_complete_map: true # 完全な地図を定期保存するかどうか。
    map_save_interval: 30.0 # 地図を保存する間隔（秒単位）。

    # --- 隠しパラメータ (デバッグや詳細なチューニングに使用) ---
    check_for_updates: true # 定期的に地図更新を確認。falseにすると更新停止。
    interpolation_buffer_size: 50 # 内挿バッファのサイズを指定。
    max_num_final_iterations: 50 # 最終的な最適化ステップの最大反復回数を設定。
    min_relative_optimization_progress: 1e-5 # 最小相対最適化進行率。進行が遅くなると停止。
    fine_to_coarse_search_distance_ratio: 0.5 # 細かい検索から粗い検索への距離比率。
    max_optimization_time: 1.0 # 各最適化ステップにかける最大時間（秒）。
    minimum_feature_search_window: 5 # 特徴量検索の最小ウィンドウサイズ。
    map_size_warn_threshold: 1000 # 地図サイズの警告閾値（単位は不明）。
    use_map_saver_service: true # 地図保存サービスの使用を有効にするかどうか。

map_saver:
  ros__parameters:
    use_sim_time: False # シミュレーション時間を使用するかどうか。
    save_map_timeout: 5.0 # 地図保存時のタイムアウト（秒）。
    free_thresh_default: 0.25 # 空き領域とするしきい値。
    occupied_thresh_default: 0.65 # 占有
