urg_node2:
  ros__parameters:
    serial_port: '/dev/ttyACM1'
    serial_baud: 115200
    frame_id : 'mirror_lidar_link'
    calibrate_time : false
    synchronize_time : false
    publish_intensity : false
    publish_multiecho : false
    error_limit : 4
    error_reset_period : 5.0
    diagnostics_tolerance : 0.05
    diagnostics_window_time : 5.0
    time_offset : 0.0
    angle_min : -2.36
    angle_max : 2.36
    skip : 0
    cluster : 1
